/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        canvas: '#0c0c1e',
        background: '#0c0c1e',
        surface: '#161630',
        surfaceContainerLow: '#12122a',
        surfaceContainer: '#161630',
        surfaceContainerHigh: '#1e1e3a',
        surfaceContainerHighest: '#262648',
        surfaceElevated: '#1e1e3a',
        /** Legacy: main ink on canvas (NativeWind `text-primary`) */
        primary: '#f5f5f5',
        secondary: '#c8c8d8',
        muted: '#8888a0',
        onSurface: '#f5f5f5',
        onSurfaceVariant: '#c8c8d8',
        /** M3 brand / filled button (use `text-onPrimary` on top) */
        brand: '#3b82f6',
        onPrimary: '#ffffff',
        primaryContainer: '#1e3a5c',
        onPrimaryContainer: '#dbeafe',
        secondaryContainer: '#2a2a48',
        onSecondaryContainer: '#e8e8f0',
        outline: 'rgba(255,255,255,0.12)',
        outlineVariant: 'rgba(255,255,255,0.08)',
        borderSubtle: 'rgba(255,255,255,0.08)',
        borderStrong: 'rgba(255,255,255,0.16)',
        overlay: 'rgba(0,0,0,0.55)',
        overlayStrong: 'rgba(0,0,0,0.72)',
        accentBlue: '#3b82f6',
        accentOrange: '#f97316',
        accentRed: '#dc2626',
        success: '#22c55e',
        warning: '#eab308',
        error: '#ef4444',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '28px',
        pill: '999px',
      },
    },
  },
  plugins: [],
};
